In [1]:
# importing Libraries
import numpy as np

from matplotlib import pyplot as plt
import pandas as pd

In [2]:
import seaborn as sns

In [6]:
# Import our Data into a data frame
df = pd.read_csv(r"C:\Users\Admin\Desktop\My-Python-Class\Data\Homelessness.csv")

In [7]:
df.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588

In [10]:
df.tail(5)

,Unnamed: 0,region,state,individuals,family_members,state_pop
46,46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,47,Pacific,Washington,16424.0,5880.0,7523869
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,50,Mountain,Wyoming,434.0,205.0,577601

In [16]:
df_ind3 = df[df['individuals'] > 7000]

In [17]:
df_ind3

,Unnamed: 0,region,state,individuals,family_members,state_pop
2,2,Mountain,Arizona,7259.0,2606.0,7158024
4,4,Pacific,California,109008.0,20964.0,39461588
5,5,Mountain,Colorado,7607.0,3250.0,5691287
9,9,South Atlantic,Florida,21443.0,9587.0,21244317
28,28,Mountain,Nevada,7058.0,486.0,3027341
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351
37,37,Pacific,Oregon,11139.0,3337.0,4181886
38,38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
43,43,West South Central,Texas,19199.0,6111.0,28628666
47,47,Pacific,Washington,16424.0,5880.0,7523869